### PR TITLE
Auctioneer v1 content

### LINKED ISSUE #21: Document what dApps support OEV searching
We should have a page for external searchers pointing them to what are the dApps that they can build the bots for. Currently, we only have the dApp registry, but that has all protocols we've integrated and only some of them are good candidates for OEV recapture.

### PR DESCRIPTION
**Pull request by Siegrift**
Relates to https://github.com/api3dao/oev-docs/issues/43
Closes https://github.com/api3dao/oev-docs/issues/21

## Rationale

I've rewamped the OEV docs - including `/oev/`, `/searchers/` and `/dapps/` section. Some of the content was up-to-date, but since I was making severe changes, it made sense to restructure the content. My goal was to:
1. Provide a holistic overview about OEV without dwelling too much into details, but rather link to a page which can be more detailed.
2. Attract the reader groups. We have two groups in the target audience - searchers and dApps. These benefit with OEV the most.
3. Explain the OEV in multiple steps. There are multiple things - OEV Network, OEV Auctioneer and OEV support on target chain. Searching is a separate category, because even without OEV, there would be MEV searching.

LMK how this reads to you and whetever else is missing. I've tried to open up a bunch of issues for stuff I know is missing (that will be added later on).

### CODE REVIEW

**Review by dcroote — COMMENTED** [review]
Is this ready for review? I see that #45 modifies some of the same files and is a PR against this branch...

**Review by aquarat — COMMENTED** [review]
Only 40% done 😆 
One thing I'm perhaps not familiar with; the text talks about the searcher/bidder announcing a winning bid. I've assumed the auctioneers does this.

**Review by mcoetzee — COMMENTED** [review]
This is really well written. Great work Emanuel 👌

**Review by aquarat — COMMENTED** [review]
Some comments/suggestions, don't take them too seriously 🤣 
This is a lot of work, well done :)

**Pull request merged**
